#!/bin/bash

if [ -z "${TF_SECRETS_PATH}" ]; then
    if [ ! -f ./config.sh ]; then
        echo "Config file not found"
        exit 1
    fi
    source ./config.sh
fi


if [ -z "${TF_SECRETS_PATH}" ]; then
    echo "Secrets path is not set"
    exit 1
fi

if [ ! -d "${TF_SECRETS_PATH}" ]; then
    echo "Secrets path does not exists"
    exit 1
fi

show_help() {
    echo -en "\nUsage: tf-do [options] [command]\n\n"
    echo -en "Options:\n"
    echo -en "  --help          Print usage\n"
    echo -en "  --debug         set -x this script\n"
    echo -en "  --environment   Sets environment. Defaults to stage\n"
    echo -en "Commands:\n"
    echo -en "  init        Terraform init\n"
    echo -en "  plan        Terraform plan\n"
    echo -en "  apply       Terraform apply\n"
    echo -en "  get         Terraform get\n"
    echo -en "  output      Terraform output\n"
    echo -en "  refresh     Terraform refresh\n"
    echo -en "  import      Terraform import\n"
}

init() {
    terraform init -input=false -upgrade=true
}

plan() {
    terraform plan -input=false -var-file="${TF_SECRETS_PATH}/terraform.tfvars" "${@}"
}

apply() {
    terraform apply -input=false -var-file="${TF_SECRETS_PATH}/terraform.tfvars" "${@}"
}

get() {
    terraform get -update=true
}

output() {
    terraform output "${@}"
}

refresh() {
    terraform refresh -var-file="${TF_SECRETS_PATH}/terraform.tfvars" "${@}"
}

destroy() {
    terraform destroy -var-file="${TF_SECRETS_PATH}/terraform.tfvars" "${@}"
}

import() {
  terraform import -var-file="${TF_SECRETS_PATH}/terraform.tfvars" "${@}"
}

while [ "$1" != "" ]; do
    case "$1" in
        -x | --debug | --setx )
            set -x
        ;;
        -h | --help | help )
            show_help
            exit 0
        ;;
        -e | --environment )
            export MY_ENVIRONMENT=${2:-stage}
            shift
        ;;
        init )
            init
            GOT_COMMAND=1
        ;;
        get )
            get
            GOT_COMMAND=1
        ;;
        plan )
            shift
            plan "${@}"
            GOT_COMMAND=1
        ;;
        apply )
            shift
            apply "${@}"
            GOT_COMMAND=1
        ;;
        output )
            shift
            output "${@}"
            GOT_COMMAND=1
        ;;
        refresh )
            shift
            refresh  "${@}"
            GOT_COMMAND=1
        ;;
        destroy )
            shift
            destroy "${@}"
            GOT_COMMAND=1
        ;;
        import )
            shift
            import "${@}"
            GOT_COMMAND=1
        ;;
    esac
    shift
done

# If we did not get a valid command print the help message
if [ "${GOT_COMMAND:-0}" == 0 ]; then
    show_help
    exit 1
fi
